### ISSUE TITLE
感谢博主分享，可以一块讨论一下么？微信应用号社区 511389428

### ISSUE THREAD

**Issue by glossary95** [Aufree/awesome-wechat-weapp#1]
感谢博主分享，可以一块讨论一下么？微信应用号社区 511389428

**Comment by Aufree** [comment]
可以扫码加微信详聊 :)

![](https://cloud.githubusercontent.com/assets/324764/18769116/e6c33c30-815c-11e6-8d34-5a50b7f4af74.png)
