### ISSUE TITLE
为什么此项目不再维护？是因为舆论的压力吗？

### ISSUE THREAD

**Issue by bodyno** [Aufree/awesome-wechat-weapp#16]
如果是因为精力不够，完全可以继续接受pr。
不再维护这是代表作者默认了某些东西？
里面有什么不可告人的秘密吗？

**Comment by itbaby** [comment]
一个小的Guidance ，弄的多大的事似的。 你家出ICQ,就不让别人出QQ吗？

**Comment by bodyno** [comment]
@itbaby 你说得和我不是一个话题 我想问的是为什么不再维护

**Comment by Aufree** [comment]
在 GitHub 上同时维护整理两份共同话题的资料意义不大，大家整理资料的目的都是为了方便其它人查阅，资料有一份足矣，如果持续保留两个 repo，后面提 PR 的人还需要到两边都提一遍，费时费力，对开源社区也没有一点好处。

另外，关于本起事件已经通过线下沟通，证明是误会一场，辛苦各位费心挂记啦。

[关于这两天的抄袭事件声明](https://laravel-china.org/topics/2925)

**Comment by bodyno** [comment]
原来如此

**Comment by itbaby** [comment]
如来缘此

**Comment by poberwong** [comment]
哎....... 好好的一个库，凭什么，凭什么啊？ justjavac没有错，你更没错.....凭什么啊？？？
